### ISSUE TITLE
https://stedit.app is broken

### ISSUE THREAD

**Issue by xyzaf1** [Offroaders123/Smart-Text-Editor#11]
![Bild_2023-05-01_170625434](https://user-images.githubusercontent.com/115548876/235473695-c01143fb-bb73-47db-be40-ac20d7fe295c.png)

**Comment by Offroaders123** [comment]
I had to do a hosting change for my menu component, and there was a small layover where it wouldn't be able to load it from the network. It may have cached that broken version on accident at some point during that layover.

It can be repaired back to normal by clearing the offline cache for `stedit.app` in DevTools.
Sorry about the issue!
<img width="1076" alt="Clear offline cache" src="https://user-images.githubusercontent.com/65947371/235497635-33b8cf64-1884-42f8-922c-da73ac5ea8aa.png">

**Comment by xyzaf1** [comment]
no problem dude, i found out its only there if im using opera gx, on opera (non gx) it works fine. btw, one of my fav open source projects this year

**Comment by Offroaders123** [comment]
Thank you! That means a lot. I am getting things more prepared for new features again, so feel free to let me know if you have any cool ideas that may be neat to add!

**Comment by tomayac** [comment]
Did you let the domain lapse? https://stedit.app/ doesn't resolve anymore. I'd love to continue [featuring the app on the Project Fugu API Showcase](https://developer.chrome.com/docs/capabilities/fugu-showcase?text=smart%20text%20editor).

**Comment by Offroaders123** [comment]
Oops, nice catch thank you! Just noticed this too.

Went and renewed the domain, it moved over to Squarespace once Google Domains closed. Auto-renew is back on again, so it will be good again for next time around.

**Comment by Offroaders123** [comment]
I'll keep this thread up to date for when it seems to be back up again. (Unfortunate to find out this way), glad to know STE is still used elsewhere! I wasn't sure if I should still keep the custom domain or not.

**Comment by Offroaders123** [comment]
Ok, things seem to be back up again, sorry for the downtime. I'll leave this open in the meantime just to ensure it seems widely available again for everyone else as well.
