### ISSUE TITLE
Offline version of Smart-Text-Editor

### ISSUE THREAD

**Issue by xnbox** [Offroaders123/Smart-Text-Editor#6]
Can we have completely offline version of Smart-Text-Editor?

**Comment by kallyluv** [comment]
> Can we have completely offline version of Smart-Text-Editor?

Smart Text Editor has an offline mode! Just install the PWA or (if on mobile) add it to your home screen. It will automatically store the app’s data in the cache for you to use offline!

**Comment by Offroaders123** [comment]
If your browser supports Service Workers, Smart Text Editor will automatically cache it's files so you can continue working while offline! To check if the site is ready for offline use, the option "Clear Cache" should be present in Smart Text Editor's settings menu. The site has the ability to work offline in both the standard browser view and the installed web app view!

<img width="200" alt="Clear Cache Setting Screenshot" src="https://user-images.githubusercontent.com/65947371/129095001-5c4b26f5-35c4-45cf-bbbc-07557f6eab44.png">

**Comment by Offroaders123** [comment]
In regards to having a completely offline release, there haven't been any concrete plans on making another version. I have looked into making a separate Electron package a few months ago, but I didn't see many benefits to going there as well as the web, considering many of the latest PWA APIs have made features like accessing the file system much more powerful than before.

However, if you have any use cases you'd like that are only available from a completely offline approach, I'd be happy to hear about them!

**Comment by xnbox** [comment]
I would like to wrap the Smart-Text-Editor as desktop application. I work on TommyBox project (see my repo), that similar to Electron, but in Java world. I would like to see hows the editor will look as real desktop app. There are lot of benefits to have desktop app, like send text by E-Mail or directly connect to databases to obtain some info.

**Comment by kallyluv** [comment]
> I would like to wrap the Smart-Text-Editor as desktop application. I work on TommyBox project (see my repo), that similar to Electron, but in Java world. I would like to see hows the editor will look as real desktop app. There are lot of benefits to have desktop app, like send text by E-Mail or directly connect to databases to obtain some info.

We have a repo related to a desktop version [here](https://github.com/Offroaders123/Electron-Text-Editor), though I'm not entirely sure it's up to date. If you want to make a desktop app version of it you are more than welcome to, we'd love to have a variety of ways to use the editor.
